---
title: "Day 2"
author: "Amy Heather"
date: "2024-08-01"
categories: [setup, read, scope]
bibliography: ../../../quarto_site/references.bib
---

::: {.callout-note}

Upload materials, read article, and define scope. Total time used: 1h 41m (4.2%)

:::

## 09.44-09.48, 09.52-09.56: Upload journal article and artefacts

The article is published at <https://link.springer.com/article/10.1007/s40258-020-00616-2>. I could not identify a copyright statement, but it links to RightsLink to request permission to reuse content (which requires payment).

Found the article on ProQuest - <https://uoelibrary.idm.oclc.org/login?url=https://www.proquest.com/scholarly-journals/cost-effectiveness-case-detection-strategies/docview/2493869343/se-2?accountid=10792> - which states copyright pringer Nature B.V. Mar 2021.

Also identified a conference abstract on the same topic <https://www.valueinhealthjournal.com/article/S1098-3015(20)31530-8/fulltext>.

As such, it appears I would not have permissions to upload this article or any images from the article to this repository. As I cannot identify a green open-access version of the article, I will just be able to include cited text quotations.

## 10.38-10.47: Consensus on upload of code

RE: my uncertainty yesterday as to uploading code with commits more recent than the publication date, I discussed this with Tom, and we agreed that I should take a similar approach to as we do when we make environments for projects without them: start with the latest version of the code, and then if things don't work, potentially go back in the commit history to help resolve it.

As such, I then uploaded a copy of the relevant branch of the repository to `original_study/`.

## 10.50-10.52: Update license

Switch to GNU General Public License version 3 to match original study. The [requirements of this license](https://fossa.com/blog/open-source-software-licenses-101-gpl-v3/) are to:

* Include a copy of the full license
* State all significant changes made to the software
* Make the original source code available when distributing binaries based on that work
* Include a copy of the original copyright notice

It allows the code to be changed and distributed to others (as long as release under GPL v3 also).

## 10.53-11.01: Complete page about original study and license

As cannot upload anything from the study, just provided links.

## 11.09-11.22, 11.29-11.38, 12.04-12.24: Read the article and outline scope

Read through the article and identified scope as:

* Table 3
* Figure 3
* Supp Appendix 6 (Figure)
* Figure 4
* Supp Appendix 7 (Figure)

There was one section of text not explicitly in the tables or figures, but it is an easy calculation from the values in Table 3, and so I feel the reproduction of Table 3 encompasses it. This was:

> "This scenario (S1a) was associated with an incremental cost of $188 and an incremental effectiveness of 0.009 QALYs per eligible patient relative to the CDQ ≥ 16.5 points among ever smokers at 5-year intervals (S3b), resulting in an ICER of $22,044/QALY."
> 
> * This is just calculated from the table - $2438 - $2250 = $188
> * 12.560 - 12.552 = 0.008 (likely rounding related)
> * ICER = 188 / 0.008 = $23,500/QALY

I outlined this on the `scope.qmd` page.

Tom later emailed to confirm he was likewise happy with this scope.

## Timings

```{python}
import sys
sys.path.append('../')
from timings import calculate_times

# Minutes used prior to today
used_to_date = 32

# Times from today
times = [
    ('09.44', '09.48'),
    ('09.52', '09.56'),
    ('10.38', '10.47'),
    ('10.50', '10.52'),
    ('10.53', '11.01'),
    ('11.09', '11.22'),
    ('11.29', '11.38'),
    ('12.04', '12.24')]

calculate_times(used_to_date, times)
```