---
title: "STARS framework"
bibliography: ../quarto_site/references.bib
---

This page evaluates the extent to which the original study meets the recommendations from the STARS framework for the sharing of code and associated materials from discrete-event simulation models (@monks_towards_2024).

Of the **8** essential STARS components:

* **4** were met fully (✅)
* **2** were met partially (🟡)
* **2** were not met (❌)

Of the **5** optional STARS components:

* **5** were not met (❌)

| Component | Description | Met by study? | Evidence/location |
| - | - | :-: | - |
| **Essential components** |
| Open license | Free and open-source software (FOSS) license (e.g. MIT, GNU Public License (GPL)) | ✅ Fully | GNU-3 |
| Dependency management | Specify software libraries, version numbers and sources (e.g. dependency management tools like virtualenv, conda, poetry) | 🟡 Partially | Rationale for partial rating:<br>• Instructions in GitHub were to install this directly from GitHub (which would install dependencies too) but that is not possible as it depends on rredis as an Import but that has been archived and so requires remotes to install<br>• Some of the dependencies used in the `.Rmd` files for the analysis were not in DESCRIPTION (as well as some dependencies that appeared as missing import errors)<br>• Doesn't specify all versions (which, although not necessary to run, would be helpful as a "snapshot" of what the analysis ran with for the paper). |
| FOSS model | Coded in FOSS language (e.g. R, Julia, Python) | ✅ Fully | R |
| Minimum documentation | Minimal instructions (e.g. in README) that overview (a) what model does, (b) how to install and run model to obtain results, and (c) how to vary parameters to run new experiments | 🟡 Partially | README has mini description of model, and clear instructions on how to install and run model, but doesn't explain how to vary parameters, and so have marked as partially met. |
| ORCID | ORCID for each study author | ❌ Not met | - |
| Citation information | Instructions on how to cite the research artefact (e.g. CITATION.cff file) | ✅ Fully | Includes instructions for citation. |
| Remote code repository | Code available in a remote code repository (e.g. GitHub, GitLab, BitBucket) | ✅ Fully | <https://github.com/KateJohnson/epicR/tree/closed_cohort> |
| Open science archive | Code stored in an open science archive with FORCE11 compliant citation and guaranteed persistance of digital artefacts (e.g. Figshare, Zenodo, the Open Science Framework (OSF), and the Computational Modeling in the Social and Ecological Sciences Network (CoMSES Net)) | ❌ Not met | As far as I am aware. |
| **Optional components** |
| Enhanced documentation | Open and high quality documentation on how the model is implemented and works  (e.g. via notebooks and markdown files, brought together using software like Quarto and Jupyter Book). Suggested content includes:<br>• Plain english summary of project and model<br>• Clarifying license<br>• Citation instructions<br>• Contribution instructions<br>• Model installation instructions<br>• Structured code walk through of model<br>• Documentation of modelling cycle using TRACE<br>• Annotated simulation reporting guidelines<br>• Clear description of model validation including its intended purpose | ❌ Not met | - |
| Documentation hosting | Host documentation (e.g. with GitHub pages, GitLab pages, BitBucket Cloud, Quarto Pub) | ❌ Not met | - |
| Online coding environment | Provide an online environment where users can run and change code (e.g. BinderHub, Google Colaboratory, Deepnote) | ❌ Not met | The README mentions that the model is on PRISM but from the links, one doesn't work and one [links to a page](https://resp.core.ubc.ca/software/epicR) that simply has a description of the model and copy of the README. Referring to the original EPIC repository it is forked from, there is a working link to the [Peer Models Network](https://resplab.github.io/prismguide/epic.html), which contains several links and instructions on how to install epic from GitHub. This is great for helping bring together collections of models with relevant instructions and links but, from looking at it, is not an online coding environment (and is more relevant to the full EPIC repository than that for this study regardless), so marked as not met. |
| Model interface | Provide web application interface to the model so it is accessible to less technical simulation users | ❌ Not met | - |
| Web app hosting | Host web app online (e.g. Streamlit Community Cloud, ShinyApps hosting) | ❌ Not met | - |
: {tbl-colwidths="[20, 35, 20, 25]"}