---
title: "Scope"
echo: False
bibliography: ../quarto_site/references.bib
---

This page outlines the parts of the journal article (@johnson_cost_2021) which we will attempt to reproduce.

As the copyright of the article belongs to the journal (without permissions to freely share images from the article), I have simply provided quotations from the table/figure captions below. You will need to navigate to the original paper to view the items.

## Within scope

::: {.callout-note appearance="minimal" collapse=true}

## Table 3

Table 3. "Table 3 Total costs and QALYs for case detection scenarios". @johnson_cost_2021

View at: <https://link.springer.com/article/10.1007/s40258-020-00616-2/tables/4>

:::

::: {.callout-note appearance="minimal" collapse=true}

## Figure 3

Figure 3. "Cost-effectiveness plane for case detection scenarios. NoCD no case detection, S1a CDQ ≥ 17 points among all patients, S1b screening spirometry (with bronchodilator) all patients, S1c CDQ + screening spirometry (with bronchodilator) all patients, S2a screening spirometry (without bronchodilator) among symptomatic patients, S3a CDQ ≥ 19.5 points among ever smokers aged ≥ 50 years, S3b CDQ ≥ 16.5 points among ever smokers aged ≥ 50 years, S3c screening spirometry (without bronchodilator) among ever smokers aged ≥ 50 years, S3d CDQ + screening spirometry (with bronchodilator) among ever smokers aged ≥ 50 years. The solid blue line indicates the efficiency frontier, and the grey dashed line indicates the WTP threshold ($50,000 per QALY gained). The highest value scenario using the efficiency frontier approach is highlighted in red". @johnson_cost_2021

View at: <https://link.springer.com/article/10.1007/s40258-020-00616-2/figures/3>

:::

::: {.callout-note appearance="minimal" collapse=true}

## Figure 4

Figure 4. "Sensitivity analyses of the incremental net monetary benefit of case detection scenarios compared to no case detection. S1a CDQ ≥ 17 points among all patients, S1b screening spirometry (with bronchodilator) all patients, S1c CDQ + screening spirometry (with bronchodilator) all patients, S2a screening spirometry (without bronchodilator) among symptomatic patients, S3a CDQ ≥ 19.5 points among ever smokers aged ≥ 50 years, S3b CDQ ≥ 16.5 points among ever smokers aged ≥ 50 years, S3c screening spirometry (without bronchodilator) among ever smokers aged ≥ 50 years, S3d CDQ + screening spirometry (with bronchodilator) among ever smokers aged ≥ 50 years". @johnson_cost_2021

View at: <https://link.springer.com/article/10.1007/s40258-020-00616-2/figures/4>

:::

::: {.callout-note appearance="minimal" collapse=true}

## Supplementary material appendix 6

Appendix 6. "Results of the preferred case detection scenario". "Results of the preferred case detection scenario (S1a: CDQ ≥17 points delivered at 3-year intervals to all patients ≥40 years) compared to no case detection. Results are shown for a cohort of 1,000 individuals eligible to receive case detection." @johnson_cost_2021

View in supplementary material, which can be downloaded from <https://doi.org/10.1007/s40258-020-00616-2>.

:::

::: {.callout-note appearance="minimal" collapse=true}

## Supplementary material appendix 7

Appendix 7. "Results of the sensitivity analysis for discount rate". "Sensitivity analysis of the incremental net monetary benefit of case detection compared to no case detection under different rates of discounting for costs and QALYs." @johnson_cost_2021

View in supplementary material, which can be downloaded from <https://doi.org/10.1007/s40258-020-00616-2>.

:::

## Outside scope

::: {.callout-note appearance="minimal" collapse=true}

## Table 1

Table 1. "Case detection scenarios evaluated". @johnson_cost_2021

:::

::: {.callout-note appearance="minimal" collapse=true}

## Figure 1

Figure 1. "Schematic illustration of the Evaluation Platform in COPD (EPIC). Modules added to the original version of EPIC [21] in order to simulate the case detection pathway are shown in grey. Note that the payoff module (not shown) collects outcomes such as costs and quality-adjusted life years as they occur throughout the disease process. *GOLD* Global Initiative for chronic Obstructive Lung Disease". @johnson_cost_2021

:::

::: {.callout-note appearance="minimal" collapse=true}

## Figure 2

Figure 1. "Framework for applying case detection strategies". @johnson_cost_2021

:::

::: {.callout-note appearance="minimal" collapse=true}

## Table 2

Table 2. "Model parameters specific to the evaluation of case detection". @johnson_cost_2021

:::